# Generated by Django 5.2.1 on 2025-05-10 14:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_emailverifycationcodes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverifycationcodes',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
